### ISSUE TITLE
MacBook default camera not front facing

### ISSUE THREAD

**Issue by Wei-1** [voidedWarranties/openvtuber2#1]
I think this repository is very high quality.
The only problem when I am trying the repo is that my MacBook default camera is leaning to one side.
Do you have any idea why this is happening?
All other programs seem to work as usual.
Is this a cropping problem caused by the video size?

**Comment by voidedWarranties** [comment]
Hi, sorry for taking some time as this repository is no longer really actively maintained.

I think this issue was a cropping issue, like you mentioned. It should now be cropped to 640x480, instead of only capturing the top left corner of the webcam output.

Please let me know if it still doesn't work.

**Comment by Wei-1** [comment]
It is now working as intended
